name: Chess cmd

on:
  push:
    branches:
      - main  
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Run unit tests
        run: python -m unittest discover
        
      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover
          coverage report

      - name: Build executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name CMDChess main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: ./dist/CMDChess.exe

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: ./dist/CMDChess.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
